name: Progress Bar CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Update README.md
        run: node date.js > README.md
      - name: Commit change & Push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'lliujiaxun+github-actions[bot]@users.noreply.github.com'
          git commit -am "bot: update README.md automatically"
          git push
        with:
          github_token: ${{ secrets.GITHUB-PROFILE-FLOWS }}
